
- name: Link to {{ python_link }}. force ? {{ 'yes' if reinstall else 'no' }}
  file:
    src: "{{ python_bin }}"
    dest: "{{ python_link }}"
    state: link
    force: "{{ 'yes' if reinstall else 'no' }}"
  when: link == true
  tags:
    - link


- name: Link to {{ pip_link }}. force ? {{ 'yes' if reinstall else 'no' }}
  file:
    src: "{{ pip_bin }}"
    dest: "{{ pip_link }}"
    state: link
    force: "{{ 'yes' if reinstall else 'no' }}"
  when: link == true
  tags:
    - link
