---
# tasks file for python
- name: Install libselinux-python.
  package: name="libselinux-python" state="present"


- name: Check status of python-{{ version }}
  stat:
    path: "{{ python_exe }}"
  register: python
  tags:
    - link


- name: Check status of pip-{{ version }}
  stat:
    path: "/usr/local/bin/pip{{ version_short }}"
  register: pip
  tags:
    - link


- name: Force to install python-{{ version }} ? {{ "yes" if reinstall else "no" }}
  debug: var=reinstall
  when: python.stat.exists == True


- include: "install-python.yml"
  static: no
  when: python.stat.exists == False or reinstall


- include: "install-pip.yml"
  static: no
  when: pip.stat.exists == False or reinstall


- name: Finish.
  debug:
    msg: python-{{ version }} was installed already. @see {{ python_dir }}
  when: python.stat.exists == True
